package dev.paraspatil.buildpulse

import dev.paraspatil.buildpulse.model.BuildDiff
import dev.paraspatil.buildpulse.model.BuildMetrics
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date

object HtmlReportGenerator{

    fun generate(
        current : BuildMetrics,
        diff: BuildDiff?,
        outputFilePath: File,
        maxAllowedIncreaseMs: Long
    ) {
        val html = buildHtmlReport(current, diff, maxAllowedIncreaseMs)
        outputFilePath.parentFile?.mkdirs()
        outputFilePath.writeText(html)

    }
    private fun buildHtmlReport(
        current: BuildMetrics,
        diff: BuildDiff?,
        threshold: Long
    ): String {
        val timestamp = SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Date(current.buildTimestamp))
        val totalSec = current.totalBuildTimeMs / 1_000.0
return """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>BuildPulse Report - ${timestamp}</title>
       
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1> BuildPulse</h1>
            <div class="subtitle">Build Performance Report • ${timestamp} </div>
            </div>
            <div class="summary">
                <h2 class="section-title">Build Summary</h2>
                <div class="summary-grid">
                    <div class="summary-card ${getCardClass(diff?.totalDiffMs,threshold)}">
                        <div class="label">Total Build Time</div>
                        <div class="value">${"%.1f".format(totalSec)}s</div>
                            ${renderDiff(diff?.totalDiffMs,threshold)}
                    </div>
                    <div class="summary-card">
                        <div class="label"></div>Modules Built</div>
                        <div class="value">${current.modules.size}</div>
                    </div>
                    <div class="summary-card">
                        <div class="label">Tasks Executed</div>
                        <div class="value">${current.tasks.size}</div>
                    </div>
                    ${renderRegressionCard(diff,threshold)}
                </div>
            </div>
            <div class="modules">
                <h2 class="section-title">Module Breakdown</h2>
                <div class="module-list">
                    ${renderModules(current,diff,threshold)}
                </div>
            </div>
            <div  class="footer">
                Generated by BuildPulse • Threshold: ${threshold}ms 
            </div>
        </div>
    </body>
    </html>
    
""".trimIndent()
    }

    private fun getCardClass(diffMs: Long?,threshold: Long): String{
        if (diffMs == null) return ""
        return when {
            diffMs > threshold -> "regression"
            diffMs < 0 -> "improvement"
            else -> ""
        }
    }
    private fun renderDiff(diffMs: Long?,threshold: Long): String{
        if (diffMs == null) return "<div class = 'diff'>First run </div>"

        val className = when {
            diffMs > threshold -> "regression"
            diffMs > 0 -> "negative"
            diffMs < 0 -> "positive"
            else -> ""
        }
        val icon = when {
            diffMs > threshold -> "⚠️"
            diffMs > 0 -> "↗"
            diffMs < 0 -> "✅"
            else -> "="
        }
        val sign = if (diffMs>0)"+" else ""
        return "<div class ='diff $className'>$icon ${sign}${diffMs}ms</div>"

    }
    private fun renderRegressionCard(diff: BuildDiff?,threshold: Long): String{
        if (diff == null) return ""

        val regressions = diff.moduleDiffs.count{ it.value > threshold}
        val cardClass = if (regressions > 0 )"regression" else  "improvement"

        return """
            <div class="summary-card $cardClass">
                <div class="label">Regressions</div>
                <div class="value">$regressions</div>
                </div>
        """.trimIndent()
    }
    private fun renderModules(
        current: BuildMetrics,
        diff: BuildDiff?,
        threshold: Long
    ): String{
        val sorted = current.modules.entries.sortedByDescending { it.value }
        val maxTime = sorted.firstOrNull()?.value ?: 0L

        return sorted.joinToString("\n" ){(module,timeMs) ->
            val diffMs = diff?.moduleDiffs?.get(module)
            val isNew = diff?.newModules?.contains(module) == true
            val isRegression = diffMs != null && diffMs > threshold

            val badge = when  {
                isNew -> "<span class='badge'>New</span>"
                isRegression -> "<span class ='badge regression'>Regression</span>"
                diffMs != null && diffMs > 0-> "<span class ='badge improvement'>Improvement</span>"
                else -> ""
            }
            val diffHtml = if (diffMs != null) {
                val sign = if (diffMs > 0) "+" else ""
                val className = if (diffMs > threshold) "positive" else "negative"
                "<div class='module-diff diff $className'>$sign$diffMs ms from previous build</sdiv>"
            } else {
                ""
            }

            val percentage = (timeMs.toDouble() / maxTime * 100).toInt()

            """
                <div class ="module-item">
                <div class ="module-header">
                <span class="module-name">$module</span>
                $badge
                </div>
                    <div class ="module-time">${"%,d".format(timeMs)} ms </div>
                </div>
                $diffHtml
                <div class="progress-bar">
                <div class="progress-fill" style="width: $percentage%"></div>
                </div>
                </div>
                """.trimIndent()

        }
    }
}